---
version: '3.3'
services:
  web:
    build:
        context: .
    ports:
       - "80:80"
    depends_on:
       - "db"
    networks:
       - "webapp"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=hime
      - POSTGRES_PASSWORD=hime
    ports:
      - '5432:5432'
        #volumes: 
        #- db:/var/lib/postgresql/data
    networks:
      - "webapp"

networks:
        webapp:
                driver: "bridge"
